Update project_test_01.yml

diff --git a/.github/workflows/project_test_01.yml b/.github/workflows/project_test_01.yml
--- a/.github/workflows/project_test_01.yml
+++ b/.github/workflows/project_test_01.yml
@@ -7,28 +7,48 @@ on:
     inputs:
       log_errors:
         description: "Generera logg-artifact om tersterna misslyckades"
-        required: true
-        default: "true"
+        required: false
+        default: "false"
 
 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Check repository
+        uses: actions/checkout@v4 
 
-      - name: Set up Python
+      - name: Set up Python 3.11
         uses: actions/setup-python@v4
         with:
           python-version: '3.11'
 
-      - name: Install deps
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          pip install pytest pytest-cov flake8
+          || true pip install pytest pytest-cov flake8
 
       - name: Lint
         run: |
           flake8 . --exclude .venv
+      
+      - name: Run test and create logg during fails
+        id: pytest_step
+        run: |
+          # Kör pytest och spara all output
+          pytest > pytest_output.txt 2>&1 || echo "failed" > test_status.txt
+          
+          if [ -f test_status.txt ]; then
+            echo "tests_failed=true" >> $GITHUB_OUTPUT
+          else
+            echo "tests_failed=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Upload test logs (only if log_errors == 'true' and tests failed)
+        if: ${{ github.event.inputs.log_errors == 'true' && steps.set_test_output.outputs.tests_failed == 'true' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: pytest-logs
+          path: pytest_output.txt
 
       
